services:
  frps-status:
    build:
      context: .
      tags:
        - lishi0105/frps-status:latest
    image: lishi0105/frps-status:v0.1
    container_name: frps_status
    restart: unless-stopped
    ports:
      - "${STATUS_APP_BIND:-0.0.0.0}:${STATUS_APP_PORT:-28080}:8080"
    environment:
      LISTEN: "${LISTEN:-0.0.0.0:8080}"
      FRPS_HOST: "${FRPS_HOST:-frps}"
      FRPS_BIND_PORT: "${FRPS_BIND_PORT:-7000}"
      FRPS_DASHBOARD_PORT: "${FRPS_DASHBOARD_PORT:-7500}"
      FRPS_DASHBOARD_USER: "${FRPS_DASHBOARD_USER:-admin}"
      FRPS_DASHBOARD_PASSWORD: "${FRPS_DASHBOARD_PASSWORD:-}"
      STATUS_DOMAINS: "${STATUS_DOMAINS:-}"
      POLL_SECONDS: "${POLL_SECONDS:-60}"
      HOST_PUBLIC_IP: "${HOST_PUBLIC_IP:-}"
      HOST_IFACE: "${HOST_IFACE:-}"
      HOST_NET_STATS_DIR: "${HOST_NET_STATS_DIR:-/host-net-stats}"
    volumes:
      - ./data:/data
      - ./config:/config
      - ./logs:/logs
      - ./frps/certbot/conf:/etc/letsencrypt:ro
      - ${HOST_NET_STATS_MOUNT:-/sys/class/net/ens34/statistics}:/host-net-stats:ro
    networks:
      - frps_net

networks:
  frps_net:
    external: true
    name: frps_default
